THIK-32 Add user remote data source and impl
thikira/ThikiraAndroid pull request #46
Opened 2020-06-02 13:13 UTC by choi-seung-min

remote data source 및 repository 추가

2020-06-02 13:25 UTC, KRMKGOLD requested changes

2020-06-02 13:25 UTC, KRMKGOLD commented on user-app/base/src/main/java/com/example/base/App.kt
> +                    accountModule
그분께서 주석은 적폐라고 하셨습니다.

2020-06-02 13:25 UTC, KRMKGOLD commented on user-app/data/api/src/main/java/com/example/api/ThikiraApi.kt
> +    suspend fun register(@Body body: Any)
Any로 한 이유가 있나요 ? 만약 빈 객체를 받아야 한다면 ResponseBody 등이 있습니다.

2020-06-02 13:25 UTC, KRMKGOLD commented on user-app/data/api/src/main/java/com/example/api/ThikiraApi.kt
> +    suspend fun login(@Body body: Any): TokenResponse
여기도요

2020-06-02 13:25 UTC, KRMKGOLD commented on user-app/data/api/src/main/java/com/example/api/datasource/RemoteAccountDataSource.kt
> +    }
괄호들 일관성
다른부분은 for {  이런식으로 하면서 try 만
```
try 
{ 

}
```
이런 방식으로 ?

2020-06-02 13:25 UTC, KRMKGOLD commented on user-app/data/api/src/main/java/com/example/api/error/ErrorHandlerImpl.kt
> +                }
when문 공백 최소화 해주면 좋을듯? 제 의견임 이건 무시해도 됨

2020-06-02 13:25 UTC, KRMKGOLD commented on user-app/data/db/build.gradle
> +}
Dep 쓰세요
DB라서 필요없는 xml들은 지워도 되나..? 아무튼 뇌피셜

2020-06-03 02:48 UTC, kimdohun0104 requested changes
메이저 이슈는 발견되지 않았습니다.
그래도 코드의 형식에 대해 많은 수정점이 있기 때문에 변경을 요청합니다.

add_parcel을 address로 네이밍을 바꾸는 것에 대한 이슈를 서버 레포에 달겠습니다

2020-06-03 02:48 UTC, kimdohun0104 commented on user-app/base/src/main/java/com/example/base/App.kt
> +                    accountModule
그런데 이 주석은 ㅇㅈ할 수 있습니다.
하지만 그냥 주석없이도 개행으로 의미를 구분할 수 있기 때문에
저도 삭제하 것에 동의합니다

2020-06-03 02:48 UTC, kimdohun0104 commented on user-app/data/api/build.gradle
> +    implementation project(path: ":error")
coreComponent, user-app, error 간에 구분을 위해 개행을 사용했으면 좋겠습니다

2020-06-03 02:48 UTC, kimdohun0104 commented on user-app/data/api/src/main/java/com/example/api/ThikiraApi.kt
> +    suspend fun register(@Body body: Any)
request를 보낼땐 따로 data class를 생성하지 않습니다.
왜냐면 복잡성과 관리가 힘들 것이라 판단하였기 때문입니다.

그래서 request에선 HashMap<String, Any> 타입으로 정보를 넘겨주게 되는데
그것을 파라미터로 명시하는 것보다 Any로 받는것이 더 간편하다 생각해였습니다

2020-06-03 02:48 UTC, kimdohun0104 commented on user-app/data/api/src/main/java/com/example/api/ThikiraApi.kt
> +    suspend fun changePassword(@Body password: String)
저는 이것이 동작하는지에 대한 의문을 가지고 있습니다. 
동작을 위해선 @Field("password") 로 변경을 해야 하지 않나요?

2020-06-03 02:48 UTC, kimdohun0104 commented on user-app/data/api/src/main/java/com/example/api/datasource/RemoteAccountDataSource.kt
> +        }
try {
} catch() {
}
와 같은 형식을 원합니다. 
너무 세로로 비대한 코드가 만들어집니다

2020-06-03 02:48 UTC, kimdohun0104 commented on user-app/data/api/src/main/java/com/example/api/datasource/RemoteAccountDataSource.kt
> +    }
try도 for 와 같은 방식으로 개행을 하지 않는것이 좋겠습니다

2020-06-03 02:48 UTC, kimdohun0104 commented on user-app/data/api/src/main/java/com/example/api/response/UserResponse.kt
> +    val roadAddress: String,
add_parcel이라는 네이밍을 서버 개발자와 상의해서 나중에 바꾸면 좋겠습니다.
저도 address, roadAddress 가 더 의미를 크게 가지고 있다고 생각합니다.
제가 서버 레포지토리에 이슈를 통해 달아놓겠습니다.
단어의 선택은 통일하는 것이 좋으니깐요

2020-06-03 02:48 UTC, kimdohun0104 commented on user-app/data/db/build.gradle
> +}
apply from: rootProjct.file() 이거 적용해주세요

2020-06-03 02:48 UTC, kimdohun0104 commented on user-app/data/db/build.gradle
> +    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
아직 사용하지 않기 때문에 삭제해주세요
'나중에 개발할 때 바꿔야지' 라고 하는 것보단
이 부분을 다른 사람이 개발할 수 있기 때문에
정리하는 것이 좋을 것 같아요

2020-06-03 02:48 UTC, kimdohun0104 commented on user-app/data/repository/build.gradle
> +    implementation project(path: ':user-app:data:api')
이 부분 개행해주세요

2020-06-03 02:51 UTC, KRMKGOLD commented on user-app/data/api/src/main/java/com/example/api/ThikiraApi.kt
> +    suspend fun changePassword(@Body password: String)
유일한 매개변수 하나이기 때문에 String으로 전달하면 되기는 할 것 같지만 field가 더 적합하다고 생각합니다 22

2020-06-05 01:16 UTC, choi-seung-min commented on user-app/data/api/src/main/java/com/example/api/error/ErrorHandlerImpl.kt
> +                }
어느정도의 가독성을 위해 개행을 한채로 남기도록 하겠습니다

2020-06-05 02:45 UTC, KRMKGOLD submitted a review, later dismissed
승인
서버에서 네이밍 변경된건 적용이 되었는지 잘 모르겠네요...

2020-06-05 02:51 UTC, kimdohun0104 approved these changes

2020-06-05 02:52 UTC, KRMKGOLD approved these changes

2020-06-05 02:57 UTC, merged