THIK-21 User App Login / Sign up
thikira/ThikiraAndroid pull request #53
Opened 2020-06-15 01:58 UTC by choi-seung-min

PR for merge

2020-06-15 02:11 UTC, KRMKGOLD submitted a review, later dismissed
화려한 코드리뷰가 나를 감싸네
Dep 수정만 해주세요 그리고 user은 왜 날렸는지 모르겠는데 일단 approve 할게요

2020-06-15 02:11 UTC, KRMKGOLD commented on build.gradle
> +        classpath 'com.google.gms:google-services:4.3.3'
Dep에 추가해서 써주세요

2020-06-15 02:11 UTC, KRMKGOLD commented on user-app/data/api/src/main/java/com/example/api/di/apiModule.kt
> +            .baseUrl("https://thikira.herokuapp.com/api/")
여기서 user은 왜 날렸나요

2020-06-15 02:20 UTC, kimdohun0104 requested changes
화이팅

2020-06-15 02:20 UTC, kimdohun0104 commented on build.gradle
>          classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
Dep.GradlePlugin.kotlinGradlePlugin과 똑은 classpath이다. 아마도 firebase 자동설정을 할 때 추가된 듯 하다
삭제해주세요

2020-06-15 02:20 UTC, kimdohun0104 commented on build.gradle
> +        classpath 'com.google.gms:google-services:4.3.3'
뭐야 이것도 똑같이 삭제바람

2020-06-15 02:20 UTC, kimdohun0104 commented on user-app/base/build.gradle
>      implementation project(path: ':user-app:feature:main')
종류가 다른 모듈간에 개행을 넣어주세요

2020-06-15 02:20 UTC, kimdohun0104 commented on user-app/data/api/src/main/java/com/example/api/di/apiModule.kt
> +            .baseUrl("https://thikira.herokuapp.com/api/")
이게 왜 변경되었는지 궁금합니다

2020-06-15 02:20 UTC, kimdohun0104 commented on user-app/data/firebase/src/main/java/com/example/firebase/FirebaseAuthSourceImpl.kt
> +        Log.d("firebase_log", phoneNumber)
로그를 작성하는 코드는 master로 머지할 때 지워주세요

2020-06-15 02:20 UTC, kimdohun0104 commented on user-app/data/firebase/src/main/java/com/example/firebase/FirebaseAuthSourceImpl.kt
> +                    Log.d("firebase_log", p0.message)
로그를 삭제해주세요

2020-06-15 02:20 UTC, kimdohun0104 commented on user-app/data/firebase/src/main/java/com/example/firebase/FirebaseAuthSourceImpl.kt
> +            TimeUnit.SECONDS,
120을 FirebaseAuthSourceImpl의 상수로 변경하는 것이 더 직관적일 수 있겠네요

2020-06-15 02:20 UTC, kimdohun0104 commented on user-app/feature/account/src/main/java/com/example/account/LoginActivity.kt
> +        viewModel.startMainEvent.observe(this) { startMainActivity() }
특정 이벤트가 발생했을 때 인자로 넘겨준 클래스를 이용해 startActivity해주는 extension이 있었으면 좋겠네요
setupNavigate<MainActivity>(viewModel.startMainEvent) 이런씩으로요

2020-06-15 02:20 UTC, kimdohun0104 commented on user-app/feature/account/src/main/java/com/example/account/LoginActivity.kt
> +        viewModel.startMainEvent.observe(this) { startMainActivity() }
그리고 startMainEvent보다 navigateMainEvent라는 용어를 쓰는 것은 어떨까요?
식당앱과 공통적인 용어를 사용했으면 좋겠습니다.

2020-06-15 02:20 UTC, kimdohun0104 commented on user-app/feature/account/src/main/java/com/example/account/LoginActivity.kt
> +            startActivity(Intent(this, Register1Activity::class.java))
Anko같은 startActivity extension이 있었다면 좋겠네요

2020-06-15 02:20 UTC, kimdohun0104 commented on user-app/feature/account/src/main/java/com/example/account/Register2Activity.kt
> +class Register2Activity: BaseActivity<ActivityRegister2Binding>(){
식당앱에서는 업체를 '등록'하는 경향이 더 크기 때문에 Register라는 표현을 사용했는데
제 생각에는 유저는 signup이라는 표현이 더 어울릴 것 같습니다

2020-06-15 02:20 UTC, kimdohun0104 commented on user-app/feature/account/src/main/java/com/example/account/viewmodel/LoginViewModel.kt
> +            Log.d("debugError", e.message!!)
로그를 삭제해주세요

2020-06-15 02:20 UTC, kimdohun0104 commented on user-app/feature/account/src/main/java/com/example/account/viewmodel/RegisterViewModel.kt
> +    }
이렇게 하나의 LiveData를 가공할 때는 Transformations.map 이라는 연산자를 사용할 수 있습니다. 
하지만 LiveDataExt를 사용하면 phone.map { }으로 쉽게 변경할 수 있습니다.

2020-06-15 02:20 UTC, kimdohun0104 commented on user-app/feature/account/src/main/java/com/example/account/viewmodel/RegisterViewModel.kt
> +
이메일이 중복되지 않았음을 확인했을 때 Toast등의 처리는 아직 구현되지 못한 것인가요?

2020-06-15 02:22 UTC, choi-seung-min commented on user-app/data/api/src/main/java/com/example/api/di/apiModule.kt
> +            .baseUrl("https://thikira.herokuapp.com/api/")
지난번 URL 다시 확인하면서 날아간 것 같습니다. 수정하겠습니다.

2020-06-15 02:25 UTC, choi-seung-min commented on user-app/feature/account/src/main/java/com/example/account/viewmodel/RegisterViewModel.kt
> +
네 그렇습니다. 현재 main에서 토큰사용을 하기 때문에 급히 merge를 위해 PR을 날린겁니다.

2020-06-16 05:00 UTC, KRMKGOLD approved these changes

2020-06-16 05:00 UTC, KRMKGOLD commented on user-app/feature/account/build.gradle
> +    implementation Dep.AndroidX.LifeCycle.liveDataKtx
이거 김도훈이 띄우라고 할듯 ㅋㅋ

2020-06-16 05:14 UTC, kimdohun0104 approved these changes

2020-06-16 05:14 UTC, kimdohun0104 commented on user-app/feature/account/src/main/java/com/example/account/LoginActivity.kt
> +        viewModel.navigateEvent.observe(this) { startActivity<MainActivity>() }
삭제해도 상관 없는 코드

2020-06-16 05:16 UTC, merged