THIK-47 [Add] Auto Scroll, Infinite Scroll, Event Activity
thikira/ThikiraAndroid pull request #60
Opened 2020-06-26 11:28 UTC by KRMKGOLD

Viewpager2 자동스크롤, 무한스크롤, EventActivity 로직 추가.

2020-06-26 12:08 UTC, kimdohun0104 requested changes
화이팅입니다

2020-06-26 12:08 UTC, kimdohun0104 commented on coreComponent/androidComponent/src/main/res/values/strings.xml
> +    <string name="from_money">원 부터</string>
from won 은 어떤가요? 솔직히 둘 다 참... ㅋㅋㅋ

2020-06-26 12:08 UTC, kimdohun0104 commented on user-app/feature/main/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
이것은 아마도 자동으로 추가된 것 처럼 보이네요ㅋㅋ

2020-06-26 12:08 UTC, kimdohun0104 commented on user-app/feature/main/src/main/java/com/example/main/adapter/MainEventAdapter.kt
> +                binding.root.context.startActivity(intent)
Intent().apply {
  putExtra()
  itemView.context.startActivith(this)
}
이렇게 수정할 수 있겠네요

2020-06-26 12:08 UTC, kimdohun0104 commented on user-app/feature/main/src/main/java/com/example/main/ui/MainActivity.kt
> +    private var isRunning = true
isRunning이라는 네이밍은 그 의도를 이해하기 위해서 다른 코드를 읽었어야 합니다
그래서 isActivityyFocused 로 변경하는 것이 어떨까요?

2020-06-26 12:08 UTC, kimdohun0104 commented on user-app/feature/main/src/main/java/com/example/main/ui/MainActivity.kt
> +    }
이 부분은 상당히 흥미롭네요.
좋습니다

2020-06-26 12:09 UTC, KRMKGOLD commented on coreComponent/androidComponent/src/main/res/values/strings.xml
> +    <string name="from_money">원 부터</string>
둘다 거지같아요 이거 승민이가 봐주세요

2020-06-26 12:09 UTC, KRMKGOLD commented on user-app/feature/main/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
이건 eventactivity 거 자동으로 추가된듯 ㅋㅋ

2020-06-26 12:10 UTC, KRMKGOLD commented on user-app/feature/main/src/main/java/com/example/main/ui/MainActivity.kt
> +    private var isRunning = true
isActivityRunning 은 어떤가요? @kimdohun0104

2020-06-26 12:10 UTC, KRMKGOLD commented on user-app/feature/main/src/main/java/com/example/main/ui/MainActivity.kt
> +    }
이건 왜냐면 이벤트 액티비티나 메뉴같은곳을 돌아왔을때, isRunning을 이용해서 다시 돌아가게 합니다
autoScrolling 하는 함수 내부를 보면 while문의 조건식이 isRunning입니다.

2020-06-26 12:12 UTC, kimdohun0104 commented on user-app/feature/main/src/main/java/com/example/main/ui/MainActivity.kt
> +    private var isRunning = true
running같은 경우에는 오해의 여지가 있습니다.
만약 isRunning = false라면 무엇인가 액티비티가 종료된 느낌을 받는 것 같습니다.
그래서 다른 액티비티 등으로 가려졌을 때 액티비티에 대한 포커스를 잃었다는 표현이 더 좋아보입니다

2020-06-26 12:26 UTC, kimdohun0104 approved these changes
굿 굿 굿 구숟구둑ㄷㄷ 굳 굳 굳 구구구굿 ㅜ 굿굿

2020-06-26 12:42 UTC, choi-seung-min commented on coreComponent/androidComponent/src/main/res/values/strings.xml
> +    <string name="from_money">원 부터</string>
delivery_start_cost같은건 어떨가요 배달 가능 가격이 이 가격 이상이라는 뜻이니까

2020-06-29 07:49 UTC, KRMKGOLD commented on coreComponent/androidComponent/src/main/res/values/strings.xml
> +    <string name="from_money">원 부터</string>
다음 피쳐 개발 시에 수정할테니 일단 Merge 하겠습니다. 중요한 사항은 아닌 것 같아요.

2020-06-29 07:49 UTC, merged

2020-06-29 07:49 UTC, KRMKGOLD commented
최승민ㄹ ㅣ뷰한다면서 request인지 approve인지 안알려줘서 걍 merge함;